### ISSUE TITLE
Project doesn't build and it's unclear which branch is correct to deploy

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/lcls-plc-lfe-optics#15]
I helped with post DC-outage recovery today, uploading master branch but with the motion lib updated to v1.4.1 (because until I did that, the project refused to build).

But it is unclear to me if #13 includes important changes that should get in before we start operations again.

@slacAWallace @jsheppard95 we need to resolve this in the next week or so

**Comment by jsheppard95** [comment]
I just went through the git diffs and I believe it was right to use master. Besides library versions, it looks like the only PLC difference between this PR and master is that in master the Pitch axis has `bPowerSelf := TRUE` on startup, which is correct. It looks like this was just missed in Alex's PR. Then comparing library versions:

| pcdshub/master  | slacAWallace/pamm-2020-9-21 |
| ------------------- | ---------------------------------- |
| PMPS 0.9.0  | PMPS 0.13.1  |
| ads-ioc 0.2.5  | ads-ioc 0.3.1  |
| optics 0.0.2  | optics 0.0.0  |

The different PMPS versions resulted in slight changes to the PMPS PVs in the `lfe_optics.db`

So I believe I should have merged Alex's PR and then made additional changes to master, but it looks like I implemented the PLC changes separately and didn't update library versions. I'd say we should just keep using master but update each of the library versions to the latest, I can do this if you guys agree?

**Comment by slacAWallace** [comment]
That makes sense to me.

**Comment by ZLLentz** [comment]
closed by #16
